/**
 * Generated by Eclipse Mita 0.1.0.
 * @date 2021-06-29 11:06:59
 */


#include <string.h>
#include <inttypes.h>
#include <stdio.h>
#include <stdbool.h>
#include <BCDS_Basics.h>
#include <BCDS_Retcode.h>
#include <stdint.h>
#include "ConnectivityMQTTBroker.h"
#include "MitaExceptions.h"
#include "application.h"

#ifndef BCDS_MODULE_ID
#define BCDS_MODULE_ID 0xCAFE
#endif

int32_t x = 0;

Retcode_T initGlobalVariables_application() {
	Retcode_T exception = RETCODE_OK;
	
	if(exception != NO_EXCEPTION) return exception;
	
	return exception;
}

Retcode_T HandleEvery3Second1(void* userParameter1, uint32_t userParameter2)
{
	
	BCDS_UNUSED(userParameter1);
	BCDS_UNUSED(userParameter2);

	Retcode_T exception = NO_EXCEPTION;
	
	
	char result1244693063_buf[19] = {0};
	char *result1244693063 = result1244693063_buf;
	
	char mainHandleEvery3Second12Result1244693063_2_buf[19] = {0};
	snprintf(mainHandleEvery3Second12Result1244693063_2_buf, sizeof(mainHandleEvery3Second12Result1244693063_2_buf), "Data = %" PRId32 "", x);
	memcpy(result1244693063, mainHandleEvery3Second12Result1244693063_2_buf, sizeof(mainHandleEvery3Second12Result1244693063_2_buf));
	
	char* _newConnectivityMQTTBroker_Topik_1 = result1244693063;
	exception = ConnectivityMQTTBroker_Topik_Write(&_newConnectivityMQTTBroker_Topik_1);
	if(exception != NO_EXCEPTION) return exception;
	printf("Data = %" PRId32 "\n", x);
	x++;


	return NO_EXCEPTION;
}


