/**
 * Generated by Eclipse Mita 0.1.0.
 * @date 2021-06-29 11:06:59
 */


#ifndef MITA_TIME_H
#define MITA_TIME_H

#include <BCDS_Retcode.h>


Retcode_T SetupTime(void);

Retcode_T EnableTime(void);

Retcode_T EveryHandleEvery3Second1_Enable(void);


#endif
